### ISSUE TITLE
ERROR  [vite:vue] Element is missing end tag.

### ISSUE THREAD

**Issue by refond** [OpenResult/caskscalajs#1]
Using this project as template with the current versions of:

- npm: 8.19.2
- node: v19.0.0
- mill: 0.10.9

I obtain `ERROR  [vite:vue] Element is missing end tag.` while running `mill server.compile` where the problem arises from the sub command run: `npm run generate` in vugui.

Replacing all unclosed HTML tags: `<Nav>, <NuxtLogo>` by their corresponding HTML 5 compliant version `<Nav />, <NuxtLogo />`
fixes the error.

These tags are located in module sub-folder vuegui : 

```
├── pages
│   ├── About.vue
│   ├── Chat.vue
│   └── index.vue
```

**Comment by Magua** [comment]
Thanks for the report @refond, refreshed versions and updated vue - tags.
